### ISSUE TITLE
Fail to compile with GCC5.3 on OS X

### ISSUE THREAD

**Issue by ufownl** [Lingxi-Li/Happy_Hacking_CXX#5]
Compilation log:

```
[ufownl@RangerUFO-Macbook-Pro build]$ make
Scanning dependencies of target aggregate_wrapper
[  3%] Building CXX object test/CMakeFiles/aggregate_wrapper.dir/aggregate_wrapper.cpp.o
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp: In member function 'virtual void aggregate_wrapper_construction_Test::TestBody()':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:62:5: error: non-constant condition for static assertion
     static_assert(x.size() == 3, "");
     ^
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:62:25: error: call to non-constexpr function 'constexpr std::size_t hhxx::aggregate_wrapper<T [n]>::size() const [with T = int; long unsigned int n = 3ul; std::size_t = long unsigned int]'
     static_assert(x.size() == 3, "");
                         ^
In file included from /Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:5:0:
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:82:25: note: 'constexpr std::size_t hhxx::aggregate_wrapper<T [n]>::size() const [with T = int; long unsigned int n = 3ul; std::size_t = long unsigned int]' is not usable as a constexpr function because:
   constexpr std::size_t size() const {
                         ^
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:82:25: error: enclosing class of constexpr non-static member function 'constexpr std::size_t hhxx::aggregate_wrapper<T [n]>::size() const [with T = int; long unsigned int n = 3ul; std::size_t = long unsigned int]' is not a literal type
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:48:7: note:'hhxx::aggregate_wrapper<int [3]>' is not literal because:
 class aggregate_wrapper<T[n]> {
       ^
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:48:7: note:  'hhxx::aggregate_wrapper<int [3]>' is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:103:5: error: non-constant condition for static assertion
     static_assert(a.size() == 3, "");
     ^
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:103:25: error: call to non-constexpr function 'constexpr std::array<_Tp, _Nm>::size_type std::array<_Tp, _Nm>::size() const [with _Tp = std::unique_ptr<int>; long unsigned int _Nm = 3ul; std::array<_Tp, _Nm>::size_type = long unsigned int]'
     static_assert(a.size() == 3, "");
                         ^
In file included from /Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:8:0:
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:170:7: note: 'constexpr std::array<_Tp, _Nm>::size_type std::array<_Tp, _Nm>::size() const [with _Tp = std::unique_ptr<int>; long unsigned int _Nm = 3ul; std::array<_Tp, _Nm>::size_type = long unsigned int]' is not usable as a constexpr function because:
       size() const noexcept { return _Nm; }
       ^
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:170:7: error: enclosing class of constexpr non-static member function 'constexpr std::array<_Tp, _Nm>::size_type std::array<_Tp, _Nm>::size() const [with _Tp = std::unique_ptr<int>; long unsigned int _Nm = 3ul; std::array<_Tp, _Nm>::size_type = long unsigned int]' is not a literal type
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:89:12: note: 'std::array<std::unique_ptr<int>, 3ul>' is not literal because:
     struct array
            ^
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:89:12: note:   'std::array<std::unique_ptr<int>, 3ul>' has a non-trivial destructor
In file included from /Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:5:0:
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<T>::aggregate_wrapper(Ts&& ...) [with Ts = {std::unique_ptr<int, std::default_delete<int> >}; <template-parameter-2-2> = std::array<std::unique_ptr<int>, 3ul>; T = std::array<std::unique_ptr<int>, 3ul>]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:108:22:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error: array must be initialized with a brace-enclosed initializer
       : base{std::forward<Ts>(xs)...} {
                                     ^
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<T>::aggregate_wrapper(Ts&& ...) [with Ts = {std::unique_ptr<int, std::default_delete<int> >, std::unique_ptr<int, std::default_delete<int> >, std::unique_ptr<int, std::default_delete<int> >}; <template-parameter-2-2> = std::array<std::unique_ptr<int>, 3ul>; T = std::array<std::unique_ptr<int>, 3ul>]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:112:40:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error: array must be initialized with a brace-enclosed initializer
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error: too many initializers for 'std::array<std::unique_ptr<int>, 3ul>'
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<T>::aggregate_wrapper(Ts&& ...) [with Ts = {std::unique_ptr<int, std::default_delete<int> >, std::unique_ptr<int, std::default_delete<int> >}; <template-parameter-2-2> = std::array<std::unique_ptr<int>, 3ul>; T = std::array<std::unique_ptr<int>, 3ul>]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:167:31:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error: array must be initialized with a brace-enclosed initializer
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error: too many initializers for 'std::array<std::unique_ptr<int>, 3ul>'
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<typename std::remove_const<typename std::remove_reference< <template-parameter-1-1> >::type>::type> hhxx::wrap_aggregate(T&&) [with T = std::unique_ptr<int> [3]; typename std::remove_const<typename std::remove_reference< <template-parameter-1-1> >::type>::type = std::unique_ptr<int> [3]]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:198:50:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:96:27: error: could not convert '(std::unique_ptr<int>*)std::forward<std::unique_ptr<int> [3]>((* & x))' from 'std::unique_ptr<int>*' to 'hhxx::aggregate_wrapper<std::unique_ptr<int> [3]>'
   return std::forward<T>(x);
                           ^
make[2]: *** [test/CMakeFiles/aggregate_wrapper.dir/aggregate_wrapper.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/aggregate_wrapper.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Lingxi-Li** [comment]
Just updated the [code](https://github.com/Lingxi-Li/Happy_Hacking_CXX/blob/master/hhxx/aggregate_wrapper.hpp#L82). GCC should be happy now. clang seems to be incorrect and non-conformant to compile the original code (see [here](http://stackoverflow.com/q/35080001/1348273)).

**Comment by Lingxi-Li** [comment]
Fixed via d635a4defd0cd1fcc974f7e1d3973bf9928af13c.

**Comment by ufownl** [comment]
Unfortunately, it still can not compile.
The new compilation log:

```
[ufownl@RangerUFO-Macbook-Pro build]$ make
[  3%] Building CXX object test/CMakeFiles/aggregate_wrapper.dir/aggregate_wrapper.cpp.o
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp: In member function 'virtual void aggregate_wrapper_construction_Test::TestBody()':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:103:5: error:non-constant condition for static assertion
     static_assert(a.size() == 3, "");
     ^
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:103:25: error: call to non-constexpr function 'constexpr std::array<_Tp, _Nm>::size_type std::array<_Tp, _Nm>::size() const [with _Tp = std::unique_ptr<int>; long unsigned int _Nm = 3ul; std::array<_Tp, _Nm>::size_type = long unsigned int]'
     static_assert(a.size() == 3, "");
                         ^
In file included from /Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:8:0:
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:170:7: note: 'constexpr std::array<_Tp, _Nm>::size_type std::array<_Tp, _Nm>::size() const [with _Tp = std::unique_ptr<int>; long unsigned int _Nm = 3ul; std::array<_Tp, _Nm>::size_type = long unsigned int]' is not usable as a constexpr function because:
       size() const noexcept { return _Nm; }
       ^
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:170:7: error: enclosing class of constexpr non-static member function 'constexpr std::array<_Tp, _Nm>::size_type std::array<_Tp, _Nm>::size() const [with _Tp = std::unique_ptr<int>; long unsigned int _Nm = 3ul; std::array<_Tp, _Nm>::size_type = long unsigned int]' is not a literal type
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:89:12: note: 'std::array<std::unique_ptr<int>, 3ul>' is not literal because:
     struct array
            ^
/usr/local/Cellar/gcc/5.3.0/include/c++/5.3.0/array:89:12: note:   'std::array<std::unique_ptr<int>, 3ul>' has a non-trivial destructor
In file included from /Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:5:0:
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<T>::aggregate_wrapper(Ts&& ...) [with Ts = {std::unique_ptr<int, std::default_delete<int> >}; <template-parameter-2-2> = std::array<std::unique_ptr<int>, 3ul>; T = std::array<std::unique_ptr<int>, 3ul>]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:108:22:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error:array must be initialized with a brace-enclosed initializer
       : base{std::forward<Ts>(xs)...} {
                                     ^
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<T>::aggregate_wrapper(Ts&& ...) [with Ts = {std::unique_ptr<int, std::default_delete<int> >, std::unique_ptr<int, std::default_delete<int> >, std::unique_ptr<int, std::default_delete<int> >}; <template-parameter-2-2> = std::array<std::unique_ptr<int>, 3ul>; T = std::array<std::unique_ptr<int>, 3ul>]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:112:40:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error:array must be initialized with a brace-enclosed initializer
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error:too many initializers for 'std::array<std::unique_ptr<int>, 3ul>'
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<T>::aggregate_wrapper(Ts&& ...) [with Ts = {std::unique_ptr<int, std::default_delete<int> >, std::unique_ptr<int, std::default_delete<int> >}; <template-parameter-2-2> = std::array<std::unique_ptr<int>, 3ul>; T = std::array<std::unique_ptr<int>, 3ul>]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:167:31:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error:array must be initialized with a brace-enclosed initializer
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:41:37: error:too many initializers for 'std::array<std::unique_ptr<int>, 3ul>'
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp: In instantiation of 'hhxx::aggregate_wrapper<typename std::remove_const<typename std::remove_reference< <template-parameter-1-1> >::type>::type> hhxx::wrap_aggregate(T&&) [with T = std::unique_ptr<int> [3]; typename std::remove_const<typename std::remove_reference< <template-parameter-1-1> >::type>::type = std::unique_ptr<int> [3]]':
/Users/ufownl/Projects/Happy_Hacking_CXX/test/aggregate_wrapper.cpp:198:50:   required from here
/Users/ufownl/Projects/Happy_Hacking_CXX/hhxx/aggregate_wrapper.hpp:96:27: error:could not convert '(std::unique_ptr<int>*)std::forward<std::unique_ptr<int> [3]>((* & x))' from 'std::unique_ptr<int>*' to 'hhxx::aggregate_wrapper<std::unique_ptr<int> [3]>'
   return std::forward<T>(x);
                           ^
make[2]: *** [test/CMakeFiles/aggregate_wrapper.dir/aggregate_wrapper.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/aggregate_wrapper.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by Lingxi-Li** [comment]
As a workaround, just made aggregate_wrapper<T[n]>::size a member variable. Does it compile now?

**Comment by Lingxi-Li** [comment]
Seems a compiler bug to me. Made `aggregate_wrapper<T[n]>::size` back to a member function, but dropped the requirement that it always be usable as a constexpr function in the unit test. Closed via 45128907565a24073758291f17420a7dfd899e27.

**Comment by Lingxi-Li** [comment]
Fixed by following this [solution](http://stackoverflow.com/a/35088173/1348273).
